branches:
  - name: main
    required_status_checks:
      contexts: [surveillance-pattern-check, ai-protection]
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 2
